/** HELM design tokens — mirrors the Stitch "Autonomous Control Plane" spec. */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424754',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#727785',
        'outline-variant': '#c2c6d6',
        primary: '#0058be',
        'on-primary': '#ffffff',
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        secondary: '#565e71',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe2f9',
        'on-secondary-container': '#5c6477',
        'secondary-fixed': '#dbe2f9',
        'secondary-fixed-dim': '#bfc6dc',
        'on-secondary-fixed': '#141b2c',
        'on-secondary-fixed-variant': '#3f4759',
        tertiary: '#924700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b75b00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        error: '#ba1a1a',
        // Data-visualization slots. Categorical order is fixed and validated
        // (CVD-safe on the light surface); status hues are reserved and never
        // reused as a series color.
        viz: {
          1: '#2a78d6',
          2: '#eb6834',
          3: '#1baf7a',
          4: '#eda100',
          good: '#0ca30c',
          warning: '#fab219',
          serious: '#ec835a',
          critical: '#d03b3b',
          grid: '#e1e0d9',
          axis: '#c3c2b7',
          muted: '#898781',
        },
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', full: '9999px' },
      spacing: { gutter: '16px', 'sidebar-width': '280px', 'widget-gap': '12px', 'container-padding': '24px' },
      fontFamily: {
        headline: ['Geist', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      keyframes: {
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'pulse-ring': { '0%': { boxShadow: '0 0 0 0 currentColor', opacity: '0.5' }, '70%': { boxShadow: '0 0 0 6px transparent', opacity: '0' }, '100%': { boxShadow: '0 0 0 0 transparent', opacity: '0' } },
      },
      animation: { 'fade-up': 'fade-up 0.28s ease-out both', 'pulse-ring': 'pulse-ring 1.6s ease-out infinite' },
    },
  },
  plugins: [],
};
