"""Direct Google Ads API REST client — no vendor SDK, no `mureo`.

Talks to the Google Ads API over plain HTTPS with `httpx`, which keeps the
dependency surface to what is already installed and makes the live path
actually runnable:

  * OAuth: exchanges a stored refresh token for a short-lived access token
    and caches it until ~60s before expiry.
  * Reads: `googleAds:searchStream` with GAQL generated by `modules.ads.gaql`.
  * Writes: `campaignBudgets:mutate` for approved budget shifts.

Everything the caller gets back is honestly labelled: a failed fetch raises,
it never degrades quietly into fabricated numbers.

Credentials expected in the secret store under `google_ads`:
    client_id, client_secret, refresh_token, developer_token, customer_id,
    login_customer_id (optional — required when the account sits under an MCC)
"""

from __future__ import annotations

import logging
import re
import time
from datetime import datetime, timezone
from typing import Any

import httpx

from modules.ads.contracts import CampaignSnapshot, MetricRow, Platform

logger = logging.getLogger(__name__)

GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_ADS_API_VERSION = "v21"
GOOGLE_ADS_BASE = f"https://googleads.googleapis.com/{GOOGLE_ADS_API_VERSION}"

_REQUIRED_CREDS = ("client_id", "client_secret", "refresh_token", "developer_token", "customer_id")


class GoogleAdsError(RuntimeError):
    """Raised when the Google Ads API rejects a request or credentials are unusable."""


def normalize_customer_id(raw: str) -> str:
    """Strip dashes/spaces from a customer id (`123-456-7890` -> `1234567890`)."""
    return re.sub(r"[^0-9]", "", str(raw or ""))


class GoogleAdsClient:
    """Minimal, dependency-light Google Ads API client."""

    def __init__(
        self,
        client_id: str,
        client_secret: str,
        refresh_token: str,
        developer_token: str,
        customer_id: str,
        login_customer_id: str | None = None,
        timeout: float = 60.0,
    ) -> None:
        self.client_id = client_id
        self.client_secret = client_secret
        self.refresh_token = refresh_token
        self.developer_token = developer_token
        self.customer_id = normalize_customer_id(customer_id)
        self.login_customer_id = normalize_customer_id(login_customer_id) if login_customer_id else None
        self.timeout = timeout

        self._access_token: str | None = None
        self._access_token_expiry: float = 0.0

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def from_credentials(cls, creds: dict[str, Any], timeout: float = 60.0) -> "GoogleAdsClient":
        """Build a client from a secret-store credential dict, or explain what's missing."""
        missing = [k for k in _REQUIRED_CREDS if not creds.get(k)]
        if missing:
            raise GoogleAdsError(
                "Google Ads credentials incomplete. Missing: "
                + ", ".join(missing)
                + ". Connect the account under Settings -> Connections."
            )
        return cls(
            client_id=str(creds["client_id"]),
            client_secret=str(creds["client_secret"]),
            refresh_token=str(creds["refresh_token"]),
            developer_token=str(creds["developer_token"]),
            customer_id=str(creds["customer_id"]),
            login_customer_id=creds.get("login_customer_id") or None,
            timeout=timeout,
        )

    # ------------------------------------------------------------------
    # Auth
    # ------------------------------------------------------------------

    def _get_access_token(self) -> str:
        """Return a cached access token, refreshing it when within 60s of expiry."""
        if self._access_token and time.time() < self._access_token_expiry - 60:
            return self._access_token

        with httpx.Client(timeout=self.timeout) as client:
            resp = client.post(
                GOOGLE_TOKEN_URI,
                data={
                    "client_id": self.client_id,
                    "client_secret": self.client_secret,
                    "refresh_token": self.refresh_token,
                    "grant_type": "refresh_token",
                },
            )
        if resp.status_code != 200:
            raise GoogleAdsError(
                f"Google OAuth token refresh failed ({resp.status_code}): {resp.text[:400]}"
            )

        data = resp.json()
        token = data.get("access_token")
        if not token:
            raise GoogleAdsError(f"Google OAuth response contained no access_token: {data}")

        self._access_token = token
        self._access_token_expiry = time.time() + float(data.get("expires_in", 3600))
        return token

    def _headers(self) -> dict[str, str]:
        headers = {
            "Authorization": f"Bearer {self._get_access_token()}",
            "developer-token": self.developer_token,
            "Content-Type": "application/json",
        }
        if self.login_customer_id:
            headers["login-customer-id"] = self.login_customer_id
        return headers

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def search(self, query: str, customer_id: str | None = None) -> list[dict[str, Any]]:
        """Run a GAQL query via `searchStream` and return the flattened result rows."""
        cid = normalize_customer_id(customer_id or self.customer_id)
        url = f"{GOOGLE_ADS_BASE}/customers/{cid}/googleAds:searchStream"

        with httpx.Client(timeout=self.timeout) as client:
            resp = client.post(url, headers=self._headers(), json={"query": query})

        if resp.status_code != 200:
            raise GoogleAdsError(
                f"Google Ads searchStream failed ({resp.status_code}): {_summarize_error(resp)}"
            )

        payload = resp.json()
        # searchStream returns a JSON array of chunks, each holding `results`.
        chunks = payload if isinstance(payload, list) else [payload]
        rows: list[dict[str, Any]] = []
        for chunk in chunks:
            if isinstance(chunk, dict):
                rows.extend(chunk.get("results", []) or [])
        return rows

    def list_accessible_customers(self) -> list[str]:
        """Return customer ids the stored refresh token can reach (for account pickers)."""
        url = f"{GOOGLE_ADS_BASE}/customers:listAccessibleCustomers"
        headers = {
            "Authorization": f"Bearer {self._get_access_token()}",
            "developer-token": self.developer_token,
        }
        with httpx.Client(timeout=self.timeout) as client:
            resp = client.get(url, headers=headers)
        if resp.status_code != 200:
            raise GoogleAdsError(
                f"listAccessibleCustomers failed ({resp.status_code}): {_summarize_error(resp)}"
            )
        resource_names = resp.json().get("resourceNames", []) or []
        return [rn.split("/")[-1] for rn in resource_names]

    def fetch_campaign_metrics(
        self,
        date_range: str = "LAST_30_DAYS",
        status_filter: str | None = "ENABLED",
    ) -> list[MetricRow]:
        """Fetch per-campaign performance for a date range as `MetricRow`s.

        `date_range` accepts a GAQL literal (`LAST_30_DAYS`) or an explicit
        `YYYY-MM-DD,YYYY-MM-DD` pair, which becomes a `BETWEEN` clause.
        """
        query = build_campaign_query(date_range=date_range, status_filter=status_filter)
        rows = self.search(query)
        return rows_to_metrics(rows)

    def fetch_snapshot(
        self,
        date_range: str = "LAST_30_DAYS",
        status_filter: str | None = "ENABLED",
    ) -> CampaignSnapshot:
        """Fetch a full account snapshot labelled `live`."""
        rows = self.fetch_campaign_metrics(date_range=date_range, status_filter=status_filter)
        total_spend = round(sum(r.spend_inr for r in rows), 2)
        blended = (
            round(sum(r.roas * r.spend_inr for r in rows) / total_spend, 2) if total_spend > 0 else 0.0
        )
        return CampaignSnapshot(
            account_ids=[self.customer_id],
            platform=Platform.GOOGLE_ADS,
            campaigns=rows,
            total_spend_inr=total_spend,
            blended_roas=blended,
            source="live",
            timestamp=datetime.now(timezone.utc).isoformat(),
            notes=f"Google Ads customer {self.customer_id}, range {date_range}",
        )

    def fetch_budget_resource(self, campaign_id: str) -> tuple[str, float]:
        """Return `(campaign_budget_resource_name, current_daily_amount_in_currency)`."""
        safe_id = re.sub(r"[^0-9]", "", str(campaign_id))
        if not safe_id:
            raise GoogleAdsError(f"Unusable campaign id: {campaign_id!r}")
        query = (
            "SELECT campaign.id, campaign_budget.resource_name, campaign_budget.amount_micros "
            f"FROM campaign WHERE campaign.id = {safe_id}"
        )
        rows = self.search(query)
        if not rows:
            raise GoogleAdsError(f"Campaign {campaign_id} not found in customer {self.customer_id}")
        budget = rows[0].get("campaignBudget") or rows[0].get("campaign_budget") or {}
        resource_name = budget.get("resourceName") or budget.get("resource_name")
        if not resource_name:
            raise GoogleAdsError(f"Campaign {campaign_id} has no linked campaign budget resource")
        amount_micros = float(budget.get("amountMicros") or budget.get("amount_micros") or 0)
        return str(resource_name), round(amount_micros / 1_000_000.0, 2)

    # ------------------------------------------------------------------
    # Writes
    # ------------------------------------------------------------------

    def update_campaign_budget(self, campaign_id: str, new_daily_budget: float) -> dict[str, Any]:
        """Set a campaign's shared daily budget. Raises rather than faking success."""
        resource_name, _current = self.fetch_budget_resource(campaign_id)
        amount_micros = int(round(float(new_daily_budget) * 1_000_000))

        url = f"{GOOGLE_ADS_BASE}/customers/{self.customer_id}/campaignBudgets:mutate"
        body = {
            "operations": [
                {
                    "update": {"resourceName": resource_name, "amountMicros": str(amount_micros)},
                    "updateMask": "amount_micros",
                }
            ]
        }
        with httpx.Client(timeout=self.timeout) as client:
            resp = client.post(url, headers=self._headers(), json=body)

        if resp.status_code != 200:
            raise GoogleAdsError(
                f"campaignBudgets:mutate failed ({resp.status_code}): {_summarize_error(resp)}"
            )
        return resp.json()

    def verify(self) -> dict[str, Any]:
        """Cheap connectivity probe used by the Settings screen."""
        query = "SELECT customer.id, customer.descriptive_name, customer.currency_code, customer.time_zone FROM customer LIMIT 1"
        rows = self.search(query)
        if not rows:
            return {"connected": True, "customer_id": self.customer_id, "descriptive_name": ""}
        cust = rows[0].get("customer", {})
        return {
            "connected": True,
            "customer_id": str(cust.get("id", self.customer_id)),
            "descriptive_name": cust.get("descriptiveName", ""),
            "currency_code": cust.get("currencyCode", ""),
            "time_zone": cust.get("timeZone", ""),
        }


# ----------------------------------------------------------------------
# GAQL helpers + response normalization
# ----------------------------------------------------------------------

_DATE_PAIR = re.compile(r"^(\d{4}-\d{2}-\d{2})\s*(?:,|\.\.)\s*(\d{4}-\d{2}-\d{2})$")
_GAQL_LITERAL = re.compile(r"^[A-Z_]+$")


def build_campaign_query(
    date_range: str = "LAST_30_DAYS",
    status_filter: str | None = "ENABLED",
) -> str:
    """Build the campaign-performance GAQL, including conversion value for real ROAS."""
    fields = [
        "campaign.id",
        "campaign.name",
        "campaign.status",
        "campaign.advertising_channel_type",
        "metrics.cost_micros",
        "metrics.impressions",
        "metrics.clicks",
        "metrics.conversions",
        "metrics.conversions_value",
        "metrics.ctr",
        "metrics.average_cpc",
        "metrics.cost_per_conversion",
    ]

    where: list[str] = []
    if status_filter:
        clean = re.sub(r"[^A-Z_]", "", status_filter.upper())
        if clean:
            where.append(f"campaign.status = '{clean}'")

    raw = (date_range or "").strip()
    pair = _DATE_PAIR.match(raw)
    if pair:
        where.append(f"segments.date BETWEEN '{pair.group(1)}' AND '{pair.group(2)}'")
    elif _GAQL_LITERAL.match(raw.upper()):
        where.append(f"segments.date DURING {raw.upper()}")
    else:
        where.append("segments.date DURING LAST_30_DAYS")

    where_str = f" WHERE {' AND '.join(where)}" if where else ""
    return f"SELECT {', '.join(fields)} FROM campaign{where_str} ORDER BY metrics.cost_micros DESC"


def rows_to_metrics(rows: list[dict[str, Any]]) -> list[MetricRow]:
    """Convert Google Ads REST rows (camelCase) into `MetricRow`s, aggregating by campaign.

    A GAQL query segmented by date returns one row per campaign per day, so
    rows are summed per campaign and the ratio metrics are recomputed from the
    totals rather than averaged (averaging ratios would misreport the account).
    """
    agg: dict[str, dict[str, Any]] = {}

    for row in rows:
        camp = row.get("campaign", {}) or {}
        metrics = row.get("metrics", {}) or {}

        cid = str(camp.get("id", "") or "")
        if not cid:
            continue

        bucket = agg.setdefault(
            cid,
            {
                "name": camp.get("name", f"Campaign {cid}"),
                "status": str(camp.get("status", "ENABLED")).upper(),
                "channel": str(camp.get("advertisingChannelType", "") or ""),
                "cost_micros": 0.0,
                "impressions": 0,
                "clicks": 0,
                "conversions": 0.0,
                "conv_value": 0.0,
            },
        )
        bucket["cost_micros"] += float(metrics.get("costMicros", 0) or 0)
        bucket["impressions"] += int(float(metrics.get("impressions", 0) or 0))
        bucket["clicks"] += int(float(metrics.get("clicks", 0) or 0))
        bucket["conversions"] += float(metrics.get("conversions", 0) or 0)
        bucket["conv_value"] += float(metrics.get("conversionsValue", 0) or 0)

    out: list[MetricRow] = []
    for cid, b in agg.items():
        spend = round(b["cost_micros"] / 1_000_000.0, 2)
        conversions = b["conversions"]
        out.append(
            MetricRow(
                campaign_id=cid,
                campaign_name=str(b["name"]),
                platform=Platform.GOOGLE_ADS,
                spend_inr=spend,
                impressions=b["impressions"],
                clicks=b["clicks"],
                conversions=int(round(conversions)),
                roas=round(b["conv_value"] / spend, 2) if spend > 0 else 0.0,
                cpa_inr=round(spend / conversions, 2) if conversions > 0 else 0.0,
                ctr=round((b["clicks"] / b["impressions"]) * 100.0, 2) if b["impressions"] > 0 else 0.0,
                status=str(b["status"]),
            )
        )

    out.sort(key=lambda r: r.spend_inr, reverse=True)
    return out


def _summarize_error(resp: httpx.Response) -> str:
    """Pull the human-readable message out of a Google Ads error body."""
    try:
        data = resp.json()
    except Exception:
        return resp.text[:400]

    if isinstance(data, list) and data:
        data = data[0]
    if not isinstance(data, dict):
        return str(data)[:400]

    error = data.get("error", data)
    message = error.get("message", "")
    details = error.get("details", []) or []
    for detail in details:
        for failure in detail.get("errors", []) or []:
            msg = failure.get("message")
            if msg:
                message = f"{message} | {msg}" if message else msg
    return (message or str(data))[:600]
